/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ihtsdo.mysnow.querysct_ui;

import java.awt.Dimension;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;

import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.ihtsdo.mysnow.querysct_api.QuerySCT;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.StatusDisplayer;

import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;


/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.ihtsdo.mysnow.querysct_ui//ConceptDetail//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "ConceptDetailTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.ihtsdo.mysnow.querysct_ui.ConceptDetailTopComponent")
@ActionReference(path = "Menu/Window", position = 300)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_ConceptDetailAction",
preferredID = "ConceptDetailTopComponent")
@Messages({
    "CTL_ConceptDetailAction=ConceptDetail",
    "CTL_ConceptDetailTopComponent=ConceptDetail Window",
    "HINT_ConceptDetailTopComponent=ConceptDetail window"
})
public final class ConceptDetailTopComponent extends TopComponent implements LookupListener {
    private Lookup.Result<RootNode> result = null;
    private ActionMap map;
    private final QuerySCT querysct = Lookup.getDefault().lookup(QuerySCT.class);
    private final ImageIcon icon = new ImageIcon("org/ihtsdo/mysnow/querysct_ui/term.png");
    JScrollPane pane;

    public ConceptDetailTopComponent() {
        initComponents();
        setName(Bundle.CTL_ConceptDetailTopComponent());
        setToolTipText(Bundle.HINT_ConceptDetailTopComponent());
//        pane = new JScrollPane();
//        pane.add(jPanel1);
//        pane.add(jPanel2);
//        pane.add(jPanel3);
//        pane.setPreferredSize(new Dimension(380, 100));
//        pane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.toolTipText")); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(null);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jTextField1.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField1.text")); // NOI18N
        jTextField1.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField1.toolTipText")); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setDragEnabled(false);
        jTextField1.setMargin(new java.awt.Insets(0, 10, 0, 10));
        jTextField1.setVerifyInputWhenFocusTarget(false);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(167, 202, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField2.text")); // NOI18N
        jTextField2.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField2.toolTipText")); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jTextField2.setDragEnabled(false);
        jTextField2.setMaximumSize(new java.awt.Dimension(4, 20));
        jTextField2.setSelectionColor(new java.awt.Color(235, 249, 235));
        jTextField2.setVerifyInputWhenFocusTarget(false);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 204, 204));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField3.text")); // NOI18N
        jTextField3.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField3.toolTipText")); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField3.setDragEnabled(false);
        jTextField3.setMaximumSize(new java.awt.Dimension(4, 20));
        jTextField3.setVerifyInputWhenFocusTarget(false);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 204));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField4.text")); // NOI18N
        jTextField4.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField4.toolTipText")); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField4.setDragEnabled(false);
        jTextField4.setVerifyInputWhenFocusTarget(false);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 255, 204));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField5.text")); // NOI18N
        jTextField5.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField5.toolTipText")); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField5.setDragEnabled(false);
        jTextField5.setSelectionColor(new java.awt.Color(204, 255, 204));
        jTextField5.setVerifyInputWhenFocusTarget(false);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField6.text")); // NOI18N
        jTextField6.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField6.toolTipText")); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField6.setDragEnabled(false);
        jTextField6.setVerifyInputWhenFocusTarget(false);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(153, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField7.text")); // NOI18N
        jTextField7.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField7.toolTipText")); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(221, 232, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel1.border.title"), javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 12))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(12, 27));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBackground(new java.awt.Color(235, 249, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel2.border.title"), javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setToolTipText(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel2.toolTipText")); // NOI18N
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(250, 236, 236));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel3.border.title"), javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBackground(new java.awt.Color(221, 232, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel4.border.title"), javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jScrollPane1.setBackground(new java.awt.Color(221, 232, 249));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(221, 232, 249));
        jTextArea1.setColumns(48);
        jTextArea1.setRows(2);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);

        jPanel5.setBackground(new java.awt.Color(232, 232, 246));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel5.border.title"), javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(602, 73));
        jPanel5.setVerifyInputWhenFocusTarget(false);

        jScrollPane2.setBackground(new java.awt.Color(232, 232, 246));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 36));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(232, 232, 246));
        jTextArea2.setColumns(28);
        jTextArea2.setRows(1);
        jTextArea2.setTabSize(6);
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4)
                        .addComponent(jTextField5)
                        .addComponent(jTextField6)
                        .addComponent(jTextField7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTextField7.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jTextField7.AccessibleContext.accessibleDescription")); // NOI18N
        jPanel2.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel2.AccessibleContext.accessibleName")); // NOI18N
        jPanel3.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ConceptDetailTopComponent.class, "ConceptDetailTopComponent.jPanel3.AccessibleContext.accessibleName")); // NOI18N
        jPanel4.getAccessibleContext().setAccessibleName("Text Definition");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
    
//    private JTextField definitionField;
    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(RootNode.class);
        result.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    

    @Override
    public void resultChanged(LookupEvent ev) {
        Collection<? extends RootNode> allnodes = result.allInstances();
        if(!allnodes.isEmpty()){
            for(RootNode sctnode: allnodes){
            sctnode = allnodes.iterator().next();
            if(138875005==sctnode.getLookup().lookup(RootNode.class).getSctId()){
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
            }else{
                jPanel2.setVisible(true);
                jPanel3.setVisible(true);
                jPanel4.setVisible(true);
                jPanel5.setVisible(true);
            }
//            StatusDisplayer.getDefault().setStatusText(sctnode.getDisplayName());
//            System.out.println("result changes in details: " + sctnode.getDisplayName());
            jPanel1.setVisible(false);
            jPanel1.removeAll();
            addTerms(sctnode);
            adjustPanelWidthToContent(jPanel1);
            jPanel1.setVisible(true);

            jPanel2.setVisible(false);
            jPanel2.removeAll();
            addModelling(sctnode);
            adjustPanelWidthToContent(jPanel2);
            if(jPanel2.getComponentCount()!=0){
            jPanel2.setVisible(true);}
            
            jPanel3.setVisible(false);
            jPanel3.removeAll();
            addParentDescription(sctnode);
            adjustPanelWidthToContent(jPanel3);
            if(jPanel3.getComponentCount()!=0){
            jPanel3.setVisible(true);}
            
            jPanel4.setVisible(false);
            jPanel4.removeAll();
            jTextArea1.setText(null);
            addTextDefinition(sctnode);
            jPanel4.add(jTextArea1);
           
            if(!jTextArea1.getText().isEmpty()){
                 jPanel4.setVisible(true);
                 jPanel4.setAutoscrolls(true);
                 jTextArea1.setLineWrap(true);
                 jTextArea1.setWrapStyleWord(true);
                 }
            jPanel4.validate();
            jPanel4.repaint();
                 
            jPanel5.setVisible(false);
            jPanel5.removeAll();
            jTextArea2.setText(null);
            getSimpleMapRefset(sctnode);
            jPanel5.add(jTextArea2);
           
            if(!jTextArea2.getText().isEmpty()){
                 jPanel5.setVisible(true);
                 jPanel5.setPreferredSize(jPanel5.getPreferredSize());
                 jPanel5.setAutoscrolls(true);

//                 jTextArea2.setLineWrap(true);
//                 jTextArea2.setWrapStyleWord(true);
                 }
            jPanel5.validate();
            jPanel5.repaint();               
                           
           
            
            jTextField1.setText(sctnode.getLookup().lookup(RootNode.class).getFSN());
            jTextField1.setEditable(false);

            jTextField2.setText(Long.toString(sctnode.getLookup().lookup(RootNode.class).getSctId()));
            jTextField2.setEditable(false);

            int statuscode = sctnode.getLookup().lookup(RootNode.class).getStatus();
            String status;
            if (statuscode ==1){
                status="Active";
            }else{
                status="Inactive";
            }
            long primitive = sctnode.getLookup().lookup(RootNode.class).getIsPrimitive();
            String isPrimitive;
            if(primitive ==900000000000074008L){ isPrimitive = "Primitive";}
            else{isPrimitive="Defined";}
            jTextField3.setText(isPrimitive);
            jTextField3.setEditable(false);
            jTextField4.setText(status);
            jTextField4.setEditable(false);
            jTextField5.setText(sctnode.getLookup().lookup(RootNode.class).getParentCount());
            jTextField5.setEditable(false);
            jTextField6.setText(sctnode.getLookup().lookup(RootNode.class).getChildrenCount());
            jTextField6.setEditable(false);
            jTextField7.setText(sctnode.getLookup().lookup(RootNode.class).getDescendantCount());
            jTextField7.setEditable(false);
            String relSummary = querysct.getRelationshipSummary(sctnode.getLookup().lookup(RootNode.class).getSctNode());
            StatusDisplayer.getDefault().setStatusText(relSummary);
            }
        }else{
//            System.out.println("No RootNode selected. No action now.");
        }
    }

    
        // It is good idea to switch all listeners on and off when the
    // component is shown or hidden. In the case of TopComponent use:
    @Override
    protected void componentActivated() {
        
    }
    @Override
    protected void componentDeactivated() {
  //      ExplorerUtils.activateActions(manager, false);
  //      querysct.shutdownGraphDB();
    }


    private void addTerms(Node sctnode) {
        StringBuilder content = new StringBuilder();

        Collection<String> PTs = sctnode.getLookup().lookup(RootNode.class).getPTActive();
        for(String pt: PTs){
            appendLine(content, pt);
        }

       
        Collection<String> Syns = sctnode.getLookup().lookup(RootNode.class).getSynActive();
        for(String syn: Syns){
            appendLine(content, syn);
        }

        addSelectablePanelContent(jPanel1, content.toString());
        
//        Collection<String> Unspecs = sctnode.getLookup().lookup(RootNode.class).getSynActive();
//        for(String uns: Unspecs){
//            jPanel1.add(new JLabel(uns));
//            System.out.println("Syn added: " + syn);
//        }
        
    }
    
    
        private void addParentDescription(Node sctnode) {
        StringBuilder content = new StringBuilder();
        Collection<String> parentDescriptions = sctnode.getLookup().lookup(RootNode.class).getPrimitiveParentDescription();                  
        for(String pfsn: parentDescriptions){
              appendLine(content, pfsn);
        }
        addSelectablePanelContent(jPanel3, content.toString());
    }

    private void addModelling(Node sctnode) {
        StringBuilder content = new StringBuilder();
        Collection<String> Models = sctnode.getLookup().lookup(RootNode.class).getModels();
        Collection<String> parentDescriptions = sctnode.getLookup().lookup(RootNode.class).getParetDescription();                  
        for(String pfsn: parentDescriptions){
            appendLine(content, pfsn);
        }

        Map<Integer, List<String>> groupedModels = new LinkedHashMap<>();
        for (String st : Models) {
            int rg = extractRoleGroup(st);
            String details = extractModelDetails(st);
            groupedModels.computeIfAbsent(rg, k -> new ArrayList<>()).add(details);
        }

        List<String> nonGrouped = groupedModels.remove(0);
        if (nonGrouped != null) {
            for (String model : nonGrouped) {
                appendLine(content, "  " + model);
            }
        }

        List<Map.Entry<Integer, List<String>>> singleAttributeGroups = new ArrayList<>();
        List<Map.Entry<Integer, List<String>>> multiAttributeGroups = new ArrayList<>();
        for (Map.Entry<Integer, List<String>> entry : groupedModels.entrySet()) {
            if (entry.getValue().size() == 1) {
                singleAttributeGroups.add(entry);
            } else {
                multiAttributeGroups.add(entry);
            }
        }

        for (Map.Entry<Integer, List<String>> entry : singleAttributeGroups) {
            appendGroupedModels(content, entry.getValue());
        }

        for (Map.Entry<Integer, List<String>> entry : multiAttributeGroups) {
            appendGroupedModels(content, entry.getValue());
        }
        addSelectablePanelContent(jPanel2, content.toString());
    }

    private void appendGroupedModels(StringBuilder content, List<String> models) {
        if (models == null || models.isEmpty()) {
            return;
        }
        if (models.size() == 1) {
            appendLine(content, "  { " + models.get(0) + " }");
            return;
        }
        appendLine(content, "  { " + models.get(0));
        for (int i = 1; i < models.size(); i++) {
            if (i == models.size() - 1) {
                appendLine(content, "    " + models.get(i) + " }");
            } else {
                appendLine(content, "    " + models.get(i));
            }
        }
    }

    private int extractRoleGroup(String modelLine) {
        if (modelLine == null) {
            return 0;
        }
        int start = modelLine.indexOf('[');
        int end = modelLine.indexOf(']');
        if (start >= 0 && end > start) {
            try {
                return Integer.parseInt(modelLine.substring(start + 1, end).trim());
            } catch (NumberFormatException ex) {
                return 0;
            }
        }
        return 0;
    }

    private String extractModelDetails(String modelLine) {
        if (modelLine == null) {
            return "";
        }
        int delimiterIndex = modelLine.indexOf("]  ");
        if (delimiterIndex >= 0 && delimiterIndex + 3 < modelLine.length()) {
            return modelLine.substring(delimiterIndex + 3);
        }
        return modelLine;
    }
    
    private void addTextDefinition(Node sctnode) {
        Collection<String> TextDefinitions = sctnode.getLookup().lookup(RootNode.class).getTextDefinition();                  
        for(String pfsn: TextDefinitions){
//            JTextArea jtextarea = new JTextArea();
//            jtextarea.setText(pfsn);
//            jtextarea.setRows(3);
//              jPanel4.add(new JLabel(pfsn));
              if(pfsn!=null){
              jTextArea1.setText(pfsn);
              }

//            System.out.println("Parent Descriptions: " + pfsn);
            
        
    }    
    }
    
    private void getSimpleMapRefset(Node sctnode){
        Collection<String> SimpleMapRefsets = sctnode.getLookup().lookup(RootNode.class).getSimpleMapRefset();
        for(String s : SimpleMapRefsets){
            if(s!=null){
                jTextArea2.append(s);
                jTextArea2.append("\n");
            }
        }
    }

    private JTextArea createSelectableLine(String text) {
        String safeText = text == null ? "" : text;
        JTextArea textLine = new JTextArea(safeText);
        textLine.setEditable(false);
        int rowCount = Math.max(1, safeText.split("\\R", -1).length);
        textLine.setRows(rowCount);
        textLine.setLineWrap(false);
        textLine.setWrapStyleWord(false);
        textLine.setOpaque(false);
        textLine.setBorder(BorderFactory.createEmptyBorder());
        textLine.setFont(jTextField1.getFont());
        textLine.setForeground(jTextField1.getForeground());
        textLine.setAlignmentX(LEFT_ALIGNMENT);
        // Allow BoxLayout to stretch each row to panel width while keeping natural row height.
        textLine.setMaximumSize(new Dimension(Integer.MAX_VALUE, textLine.getPreferredSize().height));
        return textLine;
    }

    private void addSelectablePanelContent(javax.swing.JPanel panel, String text) {
        if (text != null && !text.isEmpty()) {
            panel.add(createSelectableLine(text));
        }
    }

    private void appendLine(StringBuilder builder, String line) {
        if (line == null || line.isEmpty()) {
            return;
        }
        if (builder.length() > 0) {
            builder.append('\n');
        }
        builder.append(line);
    }

    private void adjustPanelWidthToContent(javax.swing.JPanel panel) {
        Insets insets = panel.getInsets();
        int widestContent = 0;
        int totalContentHeight = 0;
        for (java.awt.Component component : panel.getComponents()) {
            widestContent = Math.max(widestContent, component.getPreferredSize().width);
            totalContentHeight += component.getPreferredSize().height;
        }
        int horizontalPadding = 24;
        int verticalPadding = 12;
        int preferredWidth = insets.left + insets.right + widestContent + horizontalPadding;
        int preferredHeight = insets.top + insets.bottom + totalContentHeight + verticalPadding;
        panel.setPreferredSize(new Dimension(preferredWidth, preferredHeight));
        panel.setMinimumSize(new Dimension(preferredWidth, 0));
        panel.revalidate();
        panel.repaint();
    }
    
}
